CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entries INT NOT NULL DEFAULT 0
);

CREATE TABLE login (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  hash VARCHAR(255) NOT NULL
);
